import{a as L,S as q,i as d}from"./assets/vendor-56bcefdc.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const i of r)if(i.type==="childList")for(const s of i.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(r){const i={};return r.integrity&&(i.integrity=r.integrity),r.referrerPolicy&&(i.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?i.credentials="include":r.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(r){if(r.ep)return;r.ep=!0;const i=o(r);fetch(r.href,i)}})();const S="23963114-6d0d5d874ae460d9125bacd21",v="https://pixabay.com/api/";async function u(e,t=1){return(await L(`${v}`,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}let w=new q(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250});function f(e,t){const o=document.querySelector(".gallery");t&&(o.innerHTML=""),o.innerHTML+=e.map(({largeImageURL:n,webformatURL:r,tags:i,likes:s,views:p,comments:h,downloads:b})=>`<li class="gallery-item">
  <a href="${n}" >
    <img src="${r}" alt="${i}" loading="lazy">
    </a>
    <div class="info">
      <p><b>Likes</b> ${s}</p>
      <p><b>Views</b> ${p}</p>
      <p><b>Comments</b> ${h}</p>
      <p><b>Downloads</b> ${b}</p>
    </div>
  
  </li>`).join(""),w.refresh()}function l(e){d.error({title:"Error",message:e,position:"topRight"})}function P(){const e=document.querySelector(".gallery");e.innerHTML=""}function y(){document.querySelector(".div-loader").classList.remove("hidden")}function m(){document.querySelector(".div-loader").classList.add("hidden")}function c(e){const t=document.querySelector(".btn-more");e?t.classList.remove("hidden"):t.classList.add("hidden")}document.querySelector(".gallery");let a=1,g="";document.querySelector(".search-form").addEventListener("submit",async e=>{e.preventDefault();const t=e.target.elements.images.value.trim();if(console.log(t),!t){l("Please enter a search query");return}g=t,a=1,P(),c(!1),y();try{const o=await u(t);o.hits.length===0?l("Sorry, there are no images matching your search query. Please try again!"):(f(o.hits,!0),c(o.totalHits>a*15))}catch(o){l(o.message)}finally{m()}});document.querySelector(".btn-more").addEventListener("click",async()=>{a+=1,y();try{const e=await u(g,a);e.totalHits<=a*15&&(d.info({title:"info",message:"Weare sorry, but you`ve reached the end of search result.",position:"topRight"}),c(!1)),f(e.hits);const t=document.querySelectorAll(".gallery-item");if(t.length>0){const o=t[0].getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}catch(e){l(e.message)}finally{m()}});
//# sourceMappingURL=commonHelpers.js.map
