import{a as v,S as q,i as d}from"./assets/vendor-56bcefdc.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const a of i.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function n(t){if(t.ep)return;t.ep=!0;const i=o(t);fetch(t.href,i)}})();const w="23963114-6d0d5d874ae460d9125bacd21",S="https://pixabay.com/api/";async function u(e,r=1){const o=await v(`${S}`,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}});return console.log(o.data),o.data}let H=new q(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250});function P(e,r){const o=document.querySelector(".gallery"),n=o.clientHeight;r&&(o.innerHTML=""),o.innerHTML+=e.map(({largeImageURL:i,webformatURL:a,tags:p,likes:g,views:h,comments:b,downloads:L})=>`<li class="gallery-item">
  <a href="${i}" >
    <img src="${a}" alt="${p}" loading="lazy">
    </a>
    <div class="info">
      <p><b>Likes</b> ${g}</p>
      <p><b>Views</b> ${h}</p>
      <p><b>Comments</b> ${b}</p>
      <p><b>Downloads</b> ${L}</p>
    </div>
  
  </li>`).join(""),H.refresh();const t=o.clientHeight;window.scrollBy({top:t-n,behavior:"smooth"})}function l(e){d.error({title:"Error",message:e,position:"topRight"})}function $(){const e=document.querySelector(".gallery");e.innerHTML=""}function f(){console.log("+"),document.querySelector(".div-loader").classList.remove("hidden")}function m(){console.log("-"),setTimeout(()=>{document.querySelector(".div-loader").classList.add("hidden")},2e3)}function c(e){const r=document.querySelector(".btn-more");e?r.classList.remove("hidden"):r.classList.add("hidden")}let s=1,y="";document.querySelector(".search-form").addEventListener("submit",async e=>{e.preventDefault();const r=e.target.elements.images.value.trim();if(console.log(r),!r){l("Please enter a search query");return}y=r,s=1,$(),c(!1),f();try{const o=await u(r);o.hits.length===0?l("Sorry, there are no images matching your search query. Please try again!"):(P(o.hits,!0),c(o.totalHits>s*15))}catch(o){l(o.message)}finally{m()}});document.querySelector(".btn-more").addEventListener("click",async()=>{s+=1,f();try{const e=await u(y,s);c(e.totalHits>s*15),e.totalHits<=s*15&&d.info({title:"info",message:"Weare sorry, but you`ve reached the end of search result.",position:"topRight"})}catch(e){l(e.message)}finally{m()}});
//# sourceMappingURL=commonHelpers.js.map
