import{a as L,S as q,i as u}from"./assets/vendor-56bcefdc.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const S="23963114-6d0d5d874ae460d9125bacd21",v="https://pixabay.com/api/";async function d(e,t=1){return(await L(`${v}`,{params:{key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}let w=new q(".gallery a",{caption:!0,captionsData:"alt",captionDelay:250});function m(e,t){const o=document.querySelector(".gallery");t&&(o.innerHTML=""),o.innerHTML+=e.map(({largeImageURL:a,webformatURL:r,tags:s,likes:i,views:p,comments:h,downloads:b})=>`<li class="gallery-item">
  <a href="${a}" >
    <img src="${r}" alt="${s}" loading="lazy">
    </a>
    <div class="info">
      <p><b>Likes</b> ${i}</p>
      <p><b>Views</b> ${p}</p>
      <p><b>Comments</b> ${h}</p>
      <p><b>Downloads</b> ${b}</p>
    </div>
  
  </li>`).join(""),w.refresh()}function l(e){u.error({title:"Error",message:e,position:"topRight"})}function P(){const e=document.querySelector(".gallery");e.innerHTML=""}function y(){console.log("+"),document.querySelector(".div-loader").classList.remove("hidden")}function f(){console.log("-"),setTimeout(()=>{document.querySelector(".div-loader").classList.add("hidden")},2e3)}function c(e){const t=document.querySelector(".btn-more");e?t.classList.remove("hidden"):t.classList.add("hidden")}document.querySelector(".gallery");let n=1,g="";document.querySelector(".search-form").addEventListener("submit",async e=>{e.preventDefault();const t=e.target.elements.images.value.trim();if(console.log(t),!t){l("Please enter a search query");return}g=t,n=1,P(),c(!1),y();try{const o=await d(t);o.hits.length===0?l("Sorry, there are no images matching your search query. Please try again!"):(m(o.hits,!0),c(o.totalHits>n*15))}catch(o){l(o.message)}finally{f()}});document.querySelector(".btn-more").addEventListener("click",async()=>{n+=1,y();try{const e=await d(g,n);e.totalHits<=n*15&&u.info({title:"info",message:"Weare sorry, but you`ve reached the end of search result.",position:"topRight"}),m(e.hits);const t=document.querySelectorAll(".gallery-item");if(t.length>0){const o=t[0].getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}catch(e){l(e.message)}finally{f()}});
//# sourceMappingURL=commonHelpers.js.map
